# Generated by Django 5.1.15 on 2026-06-28 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('answer_given', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.exercise')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='accounts.player')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.skill')),
            ],
            options={
                'indexes': [models.Index(fields=['player', 'created_at'], name='progress_ex_player__4d96b1_idx'), models.Index(fields=['player', 'skill'], name='progress_ex_player__11e540_idx')],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='not_started', max_length=16)),
                ('best_accuracy', models.FloatField(default=0.0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='content.lesson')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='accounts.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'lesson'), name='unique_player_lesson')],
            },
        ),
    ]
