# Generated by Django 5.1.15 on 2026-06-28 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g. 'en', 'he'", max_length=8, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('direction', models.CharField(choices=[('ltr', 'Left to right'), ('rtl', 'Right to left')], default='ltr', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image')], max_length=8)),
                ('file', models.FileField(upload_to='media_assets/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_as_source', to='content.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_as_target', to='content.language')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('matching', 'Matching'), ('listening', 'Listening'), ('typing', 'Typing')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Type-specific data: prompt mode, options, answer, etc.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='content.lesson')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vocabulary', 'Vocabulary')], default='vocabulary', max_length=20)),
                ('label', models.CharField(help_text='Human-readable, for Admin', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='content.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='content.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.unit'),
        ),
        migrations.CreateModel(
            name='VocabularyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(help_text='English word/phrase taught', max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=32)),
                ('hebrew_hint', models.CharField(blank=True, help_text='Optional Hebrew translation scaffold', max_length=255)),
                ('definition_en', models.TextField(blank=True)),
                ('example_en', models.TextField(blank=True)),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_audio', to='content.mediaasset')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_image', to='content.mediaasset')),
                ('skill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_item', to='content.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="e.g. 'target'", max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.exercise')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_items', to='content.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('exercise', 'skill'), name='unique_exercise_skill')],
            },
        ),
    ]
